title: My personal blog - Newton Karanu
email: karanunewton4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am human. I speak code. I learn, and once I do, I strive to teach what I have learnt.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Newton Karanu # add your name
author-pic: newton.jpeg
about-author: I’m a fullstack software developer who loves coffee, travel, adventure, poetry, photography and blogging.

# Contact links
email: 'karanunewton4@gmail.com' # Add your Email address
phone: '+254714895623' # Add your Phone number
website: 'newtonkaranu.me' # Add your website, do not add http://
linkedin: 'newton-kiragu' # Add your Linkedin handle
github: 'newtonkiragu' # Add your Github handle
twitter: '@KiraguNewton' # Add your Twitter handle
facebook: 'karanu.newton' # Add your Facebook handle
instagram: 'karanu.newton' # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: 'newtonkaranu-me' # Add your discus identifier

# Tracker
analytics: 'UA-133342901-1' # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/", "vendor"]
